/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as EmailVerifyOtpRouteImport } from './routes/email.verify-otp'
import { Route as DashboardTeamRouteImport } from './routes/dashboard/team'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardWorkspaceSettingsIndexRouteImport } from './routes/dashboard/workspace/settings/index'
import { Route as DashboardProjectProjectIdIndexRouteImport } from './routes/dashboard/project/$projectId/index'
import { Route as DashboardProjectProjectIdTaskBoardRouteImport } from './routes/dashboard/project/$projectId/task-board'
import { Route as DashboardProjectProjectIdSettingsRouteImport } from './routes/dashboard/project/$projectId/settings'
import { Route as DashboardProjectProjectIdDecisionBoardRouteImport } from './routes/dashboard/project/$projectId/decision-board'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailVerifyOtpRoute = EmailVerifyOtpRouteImport.update({
  id: '/email/verify-otp',
  path: '/email/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTeamRoute = DashboardTeamRouteImport.update({
  id: '/dashboard/team',
  path: '/dashboard/team',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/dashboard/settings',
  path: '/dashboard/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWorkspaceSettingsIndexRoute =
  DashboardWorkspaceSettingsIndexRouteImport.update({
    id: '/dashboard/workspace/settings/',
    path: '/dashboard/workspace/settings/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardProjectProjectIdIndexRoute =
  DashboardProjectProjectIdIndexRouteImport.update({
    id: '/dashboard/project/$projectId/',
    path: '/dashboard/project/$projectId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardProjectProjectIdTaskBoardRoute =
  DashboardProjectProjectIdTaskBoardRouteImport.update({
    id: '/dashboard/project/$projectId/task-board',
    path: '/dashboard/project/$projectId/task-board',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardProjectProjectIdSettingsRoute =
  DashboardProjectProjectIdSettingsRouteImport.update({
    id: '/dashboard/project/$projectId/settings',
    path: '/dashboard/project/$projectId/settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardProjectProjectIdDecisionBoardRoute =
  DashboardProjectProjectIdDecisionBoardRouteImport.update({
    id: '/dashboard/project/$projectId/decision-board',
    path: '/dashboard/project/$projectId/decision-board',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/email/verify-otp': typeof EmailVerifyOtpRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/project/$projectId/decision-board': typeof DashboardProjectProjectIdDecisionBoardRoute
  '/dashboard/project/$projectId/settings': typeof DashboardProjectProjectIdSettingsRoute
  '/dashboard/project/$projectId/task-board': typeof DashboardProjectProjectIdTaskBoardRoute
  '/dashboard/project/$projectId': typeof DashboardProjectProjectIdIndexRoute
  '/dashboard/workspace/settings': typeof DashboardWorkspaceSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/email/verify-otp': typeof EmailVerifyOtpRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/project/$projectId/decision-board': typeof DashboardProjectProjectIdDecisionBoardRoute
  '/dashboard/project/$projectId/settings': typeof DashboardProjectProjectIdSettingsRoute
  '/dashboard/project/$projectId/task-board': typeof DashboardProjectProjectIdTaskBoardRoute
  '/dashboard/project/$projectId': typeof DashboardProjectProjectIdIndexRoute
  '/dashboard/workspace/settings': typeof DashboardWorkspaceSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/email/verify-otp': typeof EmailVerifyOtpRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/project/$projectId/decision-board': typeof DashboardProjectProjectIdDecisionBoardRoute
  '/dashboard/project/$projectId/settings': typeof DashboardProjectProjectIdSettingsRoute
  '/dashboard/project/$projectId/task-board': typeof DashboardProjectProjectIdTaskBoardRoute
  '/dashboard/project/$projectId/': typeof DashboardProjectProjectIdIndexRoute
  '/dashboard/workspace/settings/': typeof DashboardWorkspaceSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/dashboard/settings'
    | '/dashboard/team'
    | '/email/verify-otp'
    | '/dashboard'
    | '/api/auth/$'
    | '/dashboard/project/$projectId/decision-board'
    | '/dashboard/project/$projectId/settings'
    | '/dashboard/project/$projectId/task-board'
    | '/dashboard/project/$projectId'
    | '/dashboard/workspace/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/dashboard/settings'
    | '/dashboard/team'
    | '/email/verify-otp'
    | '/dashboard'
    | '/api/auth/$'
    | '/dashboard/project/$projectId/decision-board'
    | '/dashboard/project/$projectId/settings'
    | '/dashboard/project/$projectId/task-board'
    | '/dashboard/project/$projectId'
    | '/dashboard/workspace/settings'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/dashboard/settings'
    | '/dashboard/team'
    | '/email/verify-otp'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/project/$projectId/decision-board'
    | '/dashboard/project/$projectId/settings'
    | '/dashboard/project/$projectId/task-board'
    | '/dashboard/project/$projectId/'
    | '/dashboard/workspace/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTeamRoute: typeof DashboardTeamRoute
  EmailVerifyOtpRoute: typeof EmailVerifyOtpRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  DashboardProjectProjectIdDecisionBoardRoute: typeof DashboardProjectProjectIdDecisionBoardRoute
  DashboardProjectProjectIdSettingsRoute: typeof DashboardProjectProjectIdSettingsRoute
  DashboardProjectProjectIdTaskBoardRoute: typeof DashboardProjectProjectIdTaskBoardRoute
  DashboardProjectProjectIdIndexRoute: typeof DashboardProjectProjectIdIndexRoute
  DashboardWorkspaceSettingsIndexRoute: typeof DashboardWorkspaceSettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/verify-otp': {
      id: '/email/verify-otp'
      path: '/email/verify-otp'
      fullPath: '/email/verify-otp'
      preLoaderRoute: typeof EmailVerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/team': {
      id: '/dashboard/team'
      path: '/dashboard/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof DashboardTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/workspace/settings/': {
      id: '/dashboard/workspace/settings/'
      path: '/dashboard/workspace/settings'
      fullPath: '/dashboard/workspace/settings'
      preLoaderRoute: typeof DashboardWorkspaceSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/project/$projectId/': {
      id: '/dashboard/project/$projectId/'
      path: '/dashboard/project/$projectId'
      fullPath: '/dashboard/project/$projectId'
      preLoaderRoute: typeof DashboardProjectProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/project/$projectId/task-board': {
      id: '/dashboard/project/$projectId/task-board'
      path: '/dashboard/project/$projectId/task-board'
      fullPath: '/dashboard/project/$projectId/task-board'
      preLoaderRoute: typeof DashboardProjectProjectIdTaskBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/project/$projectId/settings': {
      id: '/dashboard/project/$projectId/settings'
      path: '/dashboard/project/$projectId/settings'
      fullPath: '/dashboard/project/$projectId/settings'
      preLoaderRoute: typeof DashboardProjectProjectIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/project/$projectId/decision-board': {
      id: '/dashboard/project/$projectId/decision-board'
      path: '/dashboard/project/$projectId/decision-board'
      fullPath: '/dashboard/project/$projectId/decision-board'
      preLoaderRoute: typeof DashboardProjectProjectIdDecisionBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTeamRoute: DashboardTeamRoute,
  EmailVerifyOtpRoute: EmailVerifyOtpRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  DashboardProjectProjectIdDecisionBoardRoute:
    DashboardProjectProjectIdDecisionBoardRoute,
  DashboardProjectProjectIdSettingsRoute:
    DashboardProjectProjectIdSettingsRoute,
  DashboardProjectProjectIdTaskBoardRoute:
    DashboardProjectProjectIdTaskBoardRoute,
  DashboardProjectProjectIdIndexRoute: DashboardProjectProjectIdIndexRoute,
  DashboardWorkspaceSettingsIndexRoute: DashboardWorkspaceSettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
